# Generated by Django 5.2 on 2025-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artistes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_album", models.CharField(max_length=100)),
                ("date_sortie", models.DateField()),
                (
                    "style_musique",
                    models.CharField(
                        choices=[
                            ("rock", "Rock"),
                            ("jazz", "Jazz"),
                            ("pop", "Pop"),
                            ("rap", "Rap"),
                            ("classique", "Classique"),
                            ("metal", "Metal"),
                            ("reggae", "Reggae"),
                            ("blues", "Blues"),
                            ("electro", "Électronique"),
                            ("rnb", "R&B"),
                            ("soul", "Soul"),
                            ("funk", "Funk"),
                            ("country", "Country"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nbr_musique", models.PositiveIntegerField()),
                ("duree", models.DurationField()),
            ],
        ),
    ]
